[package]
name = "ferrum-config"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
serde = { workspace = true }
notify = "7.0"
bevy = { workspace = true }
thiserror = "2.0"

[dev-dependencies]
tempfile = "3.14"
